### ISSUE TITLE
Using git archive to follow .gitattributes export ignores

### ISSUE THREAD

**Issue by sc0ttkclark** [mklasen/zip-creation-github-action#2]
Here's the workflow I came up with for my own project that was based on yours. Thanks for putting yours together, it was a great starter one for me to build from. This isn't really a feature request or bug report, it's just me sharing in case you or anyone else finds it handy.

Here's what my workflow ended up doing:

* Uses `git archive` to follow the `.gitattributes` usage of `export-ignore` so files I don't want included in the build zip will automatically be excluded
* Unzips that archive into a new subfolder using the `repo-name`
* Zips that subfolder into a new zip file (specifically need this and the above step to ensure the final unzipped directory ends up that specific name, not as `zip-name` but `repo-name`)
* That final zip file I have will also automatically include the tag name itself

`/.github/workflows/build-zip.yml`

```yml
name: Build ZIP for new release
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Create zip
        run: |
          git archive --format=zip --worktree-attributes -9 -o ${{ github.event.repository.name }}.zip HEAD
          unzip -d ${{ github.event.repository.name }} ${{ github.event.repository.name }}.zip
          zip -9 -r ${{ github.event.repository.name }}.${{ github.ref_name }}.zip ${{ github.event.repository.name }}
      - name: Add asset to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Example:** `my-repo` has a new release that is created and tagged as `1.2.3`
**Result:** `my-repo.1.2.3.zip` is created, upon unzipping it will automatically unzip to a folder `my-repo` with the exported contents within which exclude any ignored by .gitattributes
